[package]
name = "arcanist"
version = "0.0.3"
description = "package-building daemon leveraging pkgcraft"
authors = ["Tim Harder <radhermit@gmail.com>"]
homepage = "https://github.com/pkgcraft/arcanist"
repository = "https://github.com/pkgcraft/arcanist"
readme = "README.md"
license = "MIT"
edition = "2021"
rust-version = "1.59"
autotests = false

[dependencies]
anyhow = "1.0.42"
async-stream = "0.3.2"
clap = { version = "3.0.0", default-features = false, features = ["std", "suggestions"] }
config = "0.12"
futures = "0.3.16"
pkgcraft = { path = "../pkgcraft", version = "0.0.2" }
prost = "0.9"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.26"
tokio = { version = "1.14", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
tonic = { version = "0.6.0", features = ["tls", "compression"] }
url = "2"

# pakt specific deps
log = "0.4"
once_cell = "1.8.0"
tracing = "0.1"
tracing-subscriber = "0.3.0"
tower = "0.4.8"

[build-dependencies]
tonic-build = { version = "0.6.0", features = ["compression"] }

[dev-dependencies]
assert_cmd = "2"
regex = "1"
tempfile = "3"

[lib]
name = "arcanist"
path = "src/lib/lib.rs"

[[bin]]
bench = false
path = "src/server/main.rs"
name = "arcanist"

[[bin]]
bench = false
path = "src/cli/main.rs"
name = "pakt"

[[test]]
name = "integration"
path = "tests/lib.rs"
