name: CI

on:
  push:
    branches-ignore: [audit,deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust-version: ['1.56.0', '1.58.0']

    steps:
    - name: Checkout scallop
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/scallop
        path: scallop
        submodules: true

    - name: Move scallop into expected location
      run: mv scallop ../

    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Move pkgcraft into expected location
      run: mv pkgcraft ../

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update deps
      run: cargo update

    - name: Set up rust cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ~/.rustup
          target
        key: v1-${{ github.job }}-${{ runner.os }}-rust-${{ matrix.rust-version }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: v1-${{ github.job }}-${{ runner.os }}-rust-${{ matrix.rust-version }}-cargo-

    - name: Set up rust toolchain ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        profile: minimal
        override: true
        components: rustfmt

    - name: Run tests
      run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout scallop
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/scallop
        path: scallop
        submodules: true

    - name: Move scallop into expected location
      run: mv scallop ../

    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Move pkgcraft into expected location
      run: mv pkgcraft ../

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update deps
      run: cargo update

    - name: Set up rust cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          ~/.rustup
          target
        key: v1-${{ github.job }}-${{ runner.os }}-rust-${{ matrix.rust-version }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: v1-${{ github.job }}-${{ runner.os }}-rust-${{ matrix.rust-version }}-cargo-

    - name: Set up rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.58.0'
        profile: minimal
        override: true
        components: clippy, rustfmt

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
