name: CI

on:
  push:
    branches-ignore: [audit,deploy]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: arcanist
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust-version: ['1.56.0', 'stable']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: arcanist

    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Set up rust toolchain ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        profile: minimal
        override: true
        components: rustfmt

    - name: Set up rust cache
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: arcanist
        cache-on-failure: true

    - name: Run tests
      run: cargo test

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: arcanist
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: arcanist

    - name: Checkout pkgcraft
      uses: actions/checkout@v2
      with:
        repository: pkgcraft/pkgcraft
        path: pkgcraft

    - name: Set up rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: clippy, rustfmt

    - name: Run rustfmt
      run: cargo fmt --all -- --check

    - name: Set up rust cache
      uses: Swatinem/rust-cache@v1
      with:
        working-directory: arcanist
        cache-on-failure: true

    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # workaround since working-directory isn't supported yet
        # https://github.com/actions-rs/clippy-check/issues/28
        args: --manifest-path arcanist/Cargo.toml
